main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('allMovies/', views.allMovies, name='allMovies'),
    path('favorites/', views.favorites_index, name='index'),
    path('favorites/create/', views.FavoriteCreate.as_view(), name='favorites_create'),
    path('favorites/<int:favorite_id>/', views.favorites_detail, name='detail'),
    path('favorites/<int:pk>/update/', views.FavoriteUpdate.as_view(), name='favorites_update'),
    path('favorites/<int:pk>/delete/', views.FavoriteDelete.as_view(), name='favorites_delete'),
    path('favorites/<int:favorite_id>/add_watch', views.add_watch, name='add_watch'),
    path('accounts/signup/', views.signup, name='signup'),

]

mymcu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('account/', include('django.contrib.auth.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Favorite(models.Model):
    title = models.CharField(max_length=100)
    thoughts = models.CharField(max_length=250)
    rating = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'favorite_id': self.id})

class Watch(models.Model):
    date = models.DateField('Watch Date')
    favorite = models.ForeignKey(Favorite, on_delete=models.CASCADE)

    def __str__(self):
        return f'Watched on {self.date}'

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Watch

class WatchForm(ModelForm):
    class Meta:
        model = Watch
        fields = ['date']

main_app/views.py
from django.shortcuts import render, redirect
from .models import Favorite
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import WatchForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def allMovies(request):
    return render(request, 'allMovies.html')

@login_required
def favorites_index(request):
    favorites = Favorite.objects.filter(user=request.user)
    return render(request, 'favorites/index.html', {'favorites': favorites})

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'invalid - try again'
    form = UserCreationForm()
    context = {'form': form, 'error': error_message }
    return render(request, 'registration/signup.html', context)

@login_required
def favorites_detail(request, favorite_id):
    favorite = Favorite.objects.get(id=favorite_id)
    if favorite.user_id != request.user.id:
        return redirect('allMovies')
    watch_form = WatchForm
    return render(request, 'favorites/detail.html', {
        'favorite': favorite,
        'watch_form': watch_form
    })

@login_required
def add_watch(request, favorite_id):
    form = WatchForm(request.POST)
    if form.is_valid():
        new_watch = form.save(commit=False)
        new_watch.favorite_id = favorite_id
        new_watch.save()
    return redirect('detail', favorite_id=favorite_id)


class FavoriteCreate(LoginRequiredMixin, CreateView):
    model = Favorite
    fields = ('title', 'rating', 'thoughts')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class FavoriteUpdate(LoginRequiredMixin, UpdateView):
    model = Favorite
    fields = ('rating', 'thoughts')

class FavoriteDelete(LoginRequiredMixin, DeleteView):
    model = Favorite
    success_url = '/favorites/'

main_app/templates/about.html
{% extends 'base.html' %}{% block content %}

<h1>About My MCU</h1>
<hr />
<div class="about">
<p>My MCU is a site that once you create an account will be able to keep a running list of all your favorite Marvel Cinematic Universe(MCU) Movies!</p>
<br />
<p>The 'View Movie' page allows you to look through the current released movies. The list is in the correct timeline/watch order.</p>
<br />
<p>In the future there wll be a list of all the TV shows within the MCU as well, just like the list of movies already on the site. There will also be a future Marvel projects portion of the site to allow you to visit what's to come.</p>
</div>

{% endblock %}

main_app/templates/allMovies.html
{% extends 'base.html' %}{% block content %}

<h1>All MCU Movies</h1>
<hr />
<div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="captain-america">
             <span class="card-title"><b>Captain America: The First Avenger</b></span>
             <p>2011</p>
             <hr />
             <p class="card-tabs">Steve Rogers, a rejected military soldier, transforms into Captain America after taking a dose of a "Super-Soldier serum". But being Captain America comes at a price as he attempts to take down a war monger and a terrorist organization.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="captain-marvel">
             <span class="card-title"><b>Captain Marvel</b></span>
             <p>2019</p>
             <hr />
             <p class="card-tabs">Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
<div class="card">
   <!-- 'a' tag goes here -->
        <div class="card-content" id="iron-man">
            <span class="card-title"><b>Iron Man</b></span>
            <p>2008</p>
            <hr />
            <p class="card-tabs">After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.</p>
        </div>
    <!-- close 'a' tag -->
</div>
<div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="hulk">
             <span class="card-title"><b>The Incredible Hulk</b></span>
             <p>2008</p>
             <hr />
             <p class="card-tabs">Bruce Banner, a scientist on the run from the U.S. Government, must find a cure for the monster he turns into whenever he loses his temper.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="iron-man">
             <span class="card-title"><b>Iron Man 2</b></span>
             <p>2010</p>
             <hr />
             <p class="card-tabs">With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father's legacy.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="thor">
             <span class="card-title"><b>Thor</b></span>
             <p>2011</p>
             <hr />
             <p class="card-tabs">The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="avengers">
             <span class="card-title"><b>The Avengers</b></span>
             <p>2012</p>
             <hr />
             <p class="card-tabs">Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="iron-man">
             <span class="card-title"><b>Iron Man 3</b></span>
             <p>2013</p>
             <hr />
             <p class="card-tabs">When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="thor">
             <span class="card-title"><b>Thor: The Dark World</b></span>
             <p>2013</p>
             <hr />
             <p class="card-tabs">When the Dark Elves attempt to plunge the universe into darkness, Thor must embark on a perilous and personal journey that will reunite him with doctor Jane Foster.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="captain-america">
             <span class="card-title"><b>Captain America: The Winter Soldier</b></span>
             <p>2014</p>
             <hr />
             <p class="card-tabs">As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="guardians">
             <span class="card-title"><b>Guardians of the Galaxy</b></span>
             <p>2014</p>
             <hr />
             <p class="card-tabs">A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="guardians">
             <span class="card-title"><b>Guardians of the Galaxy Vol. 2</b></span>
             <p>2017</p>
             <hr />
             <p class="card-tabs">The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father the ambitious celestial being Ego.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="avengers">
             <span class="card-title"><b>Avengers: Age of Ultron</b></span>
             <p>2015</p>
             <hr />
             <p class="card-tabs">When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="ant-man">
             <span class="card-title"><b>Ant-Man</b></span>
             <p>2015</p>
             <hr />
             <p class="card-tabs">Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, pull off a plan that will save the world.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="captain-america">
             <span class="card-title"><b>Captain America: Civil War</b></span>
             <p>2016</p>
             <hr />
             <p class="card-tabs">Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="black-widow">
             <span class="card-title"><b>Black Widow</b></span>
             <p>2021</p>
             <hr />
             <p class="card-tabs">Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="spider-man">
             <span class="card-title"><b>Spider-Man: Homecoming</b></span>
             <p>2017</p>
             <hr />
             <p class="card-tabs">Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="black-panther">
             <span class="card-title"><b>Black Panther</b></span>
             <p>2018</p>
             <hr />
             <p class="card-tabs">T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="doctor-strange">
             <span class="card-title"><b>Doctor Strange</b></span>
             <p>2016</p>
             <hr />
             <p class="card-tabs">While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="thor">
             <span class="card-title"><b>Thor: Ragnarok</b></span>
             <p>2017</p>
             <hr />
             <p class="card-tabs">Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="ant-man">
             <span class="card-title"><b>Ant-Man and the Wasp</b></span>
             <p>2018</p>
             <hr />
             <p class="card-tabs">As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="avengers">
             <span class="card-title"><b>Avengers: Infinity War</b></span>
             <p>2018</p>
             <hr />
             <p class="card-tabs">The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="avengers">
             <span class="card-title"><b>Avengers: Endgame</b></span>
             <p>2019</p>
             <hr />
             <p class="card-tabs">After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="spider-man">
             <span class="card-title"><b>Spider-Man: Far From Home</b></span>
             <p>2019</p>
             <hr />
             <p class="card-tabs">Following the events of Avengers: Endgame (2019), Spider-Man must step up to take on new threats in a world that has changed forever.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="eternals">
             <span class="card-title"><b>Eternals</b></span>
             <p>2021</p>
             <hr />
             <p class="card-tabs">The saga of the Eternals, a race of immortal beings who lived on Earth and shaped its history and civilizations.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="shang-chi">
             <span class="card-title"><b>Shang-Chi and the Legend of the Ten Rings</b></span>
             <p>2021</p>
             <hr />
             <p class="card-tabs">Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.</p>
         </div>
     <!-- close 'a' tag -->
 </div>
 <div class="card">
    <!-- 'a' tag goes here -->
         <div class="card-content" id="spider-man">
             <span class="card-title"><b>Spider-Man: No Way Home</b></span>
             <p>2021</p>
             <hr />
             <p class="card-tabs">With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.</p>
         </div>
     <!-- close 'a' tag -->
 </div>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My MCU</title>
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li>
                        <a href="/" class="left brand-logo">My MCU</a>
                    </li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'allMovies' %}">View Movies</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'index' %}">View Favorites</a></li>
                    <li><a href="{% url 'favorites_create' %}">Add Favorites</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">Log In</a></li>
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="center">
            All Rights Reserved, © 2022 My MCU
        </div>
    </footer>
</body>
</html>

main_app/templates/favorites/detail.html
{% extends 'base.html' %}{% block content %}

<h1>Movie Details</h1>
<hr />

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title"><b>{{ favorite.title }}</b></span>
                <p><b>Rating:</b> {{ favorite.rating }}</p>
                <p><b>Thoughts:</b> {{ favorite.thoughts }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'favorites_update' favorite.id %}">Edit</a>
                <a href="{% url 'favorites_delete' favorite.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_watch' favorite.id %}" method="post">
            {% csrf_token %} {{ watch_form.as_p }}
            <input type="submit" class="btn green" value="Add Watch Date" />
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Watched on: </th>
                </tr>
            </thead>
            <tbody>
                {% for watch in favorite.watch_set.all %}
                <tr>
                    <td>{{watch.date}}</td>
                    <td>{{watch.get_date_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script>
    var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
</script>


{% endblock %}

main_app/templates/favorites/index.html
{% extends 'base.html' %}{% block content %}

<h1>My Favorites</h1>
<hr />
{% for favorite in favorites %}
<div class="card">
    <a href="{% url 'detail' favorite.id %}">
    <div class="card-content">
        <span class="card-title">{{ favorite.title }}</span>
        <p>Rating: {{ favorite.rating }}</p>
        <p>Thoughts: {{ favorite.thoughts }}</p>
    </div>
    </a>
</div>

{% endfor %}
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}{% block content %}
<div class="picture">
    <h1 class="home-title">MY MCU</h1>
</div>
{% endblock %}

main_app/templates/main_app/favorite_confirm_delete.html
{% extends 'base.html' %} {% block content %}

    <h1>Remove {{object.name}}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes" class="btn red">
        <a href="{% url 'detail' object.id %}" class="btn blue">Cancel</a>
    </form>

{% endblock %}

main_app/templates/main_app/favorite_form.html
{% extends 'base.html' %}{% block content %}

{% if object %}
<h1>Edit <span>{{object.name}}</span></h1>
{% else %}
<h1>Add Movie</h1>
{% endif %}


<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn green" />
</form>


{% endblock %}

main_app/templates/main_app/favorites_confirm_delete.html
{% extends 'base.html' %} {% block content %}

    <h1>Remove {{object.name}}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes" class="btn red">
        <a href="{% url 'detail' object.id %}" class="btn blue">Cancel</a>
    </form>

{% endblock %}